# Generated by Django 4.0.4 on 2022-05-10 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_classe', models.CharField(max_length=100)),
                ('formation', models.CharField(max_length=100)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('nombre_etudiants', models.IntegerField()),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant_ajout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etudiant', models.CharField(max_length=100)),
                ('pays_naissance', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('moyenne', models.IntegerField()),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etudiant', models.CharField(max_length=100)),
                ('pays_naissance', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('moyenne', models.IntegerField()),
                ('details', models.TextField(blank=True, null=True)),
                ('classe', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='IUTdeColmar.classe')),
            ],
        ),
    ]
